ALTER TABLE users DROP COLUMN rowid;
ALTER TABLE groups DROP COLUMN rowid;
ALTER TABLE logins DROP COLUMN rowid;
ALTER TABLE history DROP COLUMN rowid;

ALTER TABLE groups ALTER COLUMN team SET NOT NULL;