-- ALTER TABLE users DROP CONSTRAINT users_pkey;
-- ALTER TABLE users DROP COLUMN rowid;
ALTER TABLE users ALTER COLUMN id SET NOT NULL;
-- ALTER TABLE users ADD PRIMARY KEY (id);
-- ALTER TABLE users DROP COLUMN rowid;
ALTER TABLE logins ALTER COLUMN id SET NOT NULL;
ALTER TABLE groups ALTER COLUMN id SET NOT NULL;
ALTER TABLE history ALTER COLUMN id SET NOT NULL;
ALTER TABLE users_teams ALTER COLUMN id SET NOT NULL;